export const PARTNER_BRANDING = {
  name: "Sykes Holiday Cottages",
  shortName: "Sykes",
  logoName: "Sykes Holiday Cottages",
  userDisplayName: "George",
  tagline: "Partner booking analytics",
  partnerId: "partner-a",
  contactEmail: "partners@sykescottages.co.uk",
  colors: {
    primary: "#006BFF",
    primaryDark: "#0054CC",
    accent: "#3389FF",
    surface: "#EEF5FF",
  },
  /** Dedicated Pikl contacts for this partner account. */
  piklPartners: [
    {
      id: "amelia",
      name: "Amelia Hart",
      role: "Partner Success Manager",
      email: "amelia.hart@pikl.com",
      phone: "+44 20 3890 2140",
      phoneDisplay: "+44 20 3890 2140",
      linkedInUrl: "https://www.linkedin.com/in/connor-greaves/",
      detail: "Day-to-day product & commercial support",
      photo: "amelia" as const,
    },
    {
      id: "james",
      name: "James Okonkwo",
      role: "Account Director",
      email: "james.okonkwo@pikl.com",
      phone: "+44 20 3890 2141",
      phoneDisplay: "+44 20 3890 2141",
      linkedInUrl: "https://www.linkedin.com/in/connor-greaves/",
      detail: "Commercial strategy & renewals",
      photo: "initials" as const,
    },
    {
      id: "priya",
      name: "Priya Shah",
      role: "Solutions Engineer",
      email: "priya.shah@pikl.com",
      phone: "+44 20 3890 2142",
      phoneDisplay: "+44 20 3890 2142",
      linkedInUrl: "https://www.linkedin.com/in/connor-greaves/",
      detail: "Integrations, data feeds & BDX",
      photo: "initials" as const,
    },
    {
      id: "support",
      name: "Pikl Support Desk",
      role: "Partner Support",
      email: "partners@pikl.com",
      phone: "0800 254 5171",
      phoneDisplay: "0800 254 5171",
      linkedInUrl: "https://www.linkedin.com/in/connor-greaves/",
      detail: "General help · claims · policy questions",
      photo: "support" as const,
    },
  ],
} as const
